In [2]:
import pandas as pd
import numpy as np
import os
import FinanceDataReader as fdr
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from tqdm import tqdm
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA
# from pandas import datetime
from pmdarima.arima import auto_arima
import statsmodels.api as sm
import warnings

In [3]:
path = './open'
list_name = 'stock_list.csv'
sample_name = 'sample_submission.csv'

stock_list = pd.read_csv(os.path.join(path,list_name))
stock_list['종목코드'] = stock_list['종목코드'].apply(lambda x : str(x).zfill(6))
stock_list

종목명    종목코드    상장시장
0        삼성전자  005930   KOSPI
1      SK하이닉스  000660   KOSPI
2       NAVER  035420   KOSPI
3         카카오  035720   KOSPI
4    삼성바이오로직스  207940   KOSPI
..        ...     ...     ...
365      맘스터치  220630  KOSDAQ
366        다날  064260  KOSDAQ
367   제이시스메디칼  287410  KOSDAQ
368   크리스에프앤씨  110790  KOSDAQ
369     쎄트렉아이  099320  KOSDAQ

[370 rows x 3 columns]

In [4]:
start_date = '20210104'
end_date = '20211031'

start_weekday = pd.to_datetime(start_date).weekday()
max_weeknum = pd.to_datetime(end_date).strftime('%V')
Business_days = pd.DataFrame(pd.date_range(start_date,end_date,freq='B'), columns = ['Date'])

print(f'WEEKDAY of "start_date" : {start_weekday}')
print(f'NUM of WEEKS to "end_date" : {max_weeknum}')
print(f'HOW MANY "Business_days" : {Business_days.shape}', )
display(Business_days.head())

WEEKDAY of "start_date" : 0
NUM of WEEKS to "end_date" : 43
HOW MANY "Business_days" : (215, 1)


Date
0 2021-01-04
1 2021-01-05
2 2021-01-06
3 2021-01-07
4 2021-01-08

In [5]:
sample_code = stock_list.loc[0,'종목코드']

sample = fdr.DataReader(sample_code, start = start_date, end = end_date)[['Close']].reset_index()
sample = pd.merge(Business_days, sample, how = 'outer')
sample['weekday'] = sample.Date.apply(lambda x : x.weekday())
sample['weeknum'] = sample.Date.apply(lambda x : x.strftime('%V'))
sample.Close = sample.Close.ffill()
sample = pd.pivot_table(data = sample, values = 'Close', columns = 'weekday', index = 'weeknum')

sample_flatten = np.ravel(sample.to_numpy())
len(sample_flatten)



215

In [6]:
# evaluate an ARIMA model for a given order (p,d,q)
def evaluate_arima_model(X, arima_order):
	# prepare training dataset
	train_size = len(X)-5
	train, test = X[0:train_size], X[train_size:]

	# make predictions
	predictions = list()
	for t in range(len(test)):
		model = ARIMA(train, order=arima_order)
		model_fit = model.fit()
		yhat = model_fit.forecast(steps=5)
		predictions.append(yhat)
	# calculate out of sample error
	error = mean_squared_error(test, predictions)
	return error

In [7]:

# evaluate combinations of p, d and q values for an ARIMA model
def evaluate_models(dataset, p_values, d_values, q_values):
	dataset = dataset.astype('float32')
	best_score, best_cfg = float("inf"), None
	for p in p_values:
		for d in d_values:
			for q in q_values:
				order = (p,d,q)
				try:
					mse = evaluate_arima_model(dataset, order)
					if mse < best_score:
						best_score, best_cfg = mse, order
					print('ARIMA%s MSE=%.3f' % (order,mse))
				except:
					continue
	print('Best ARIMA%s MSE=%.3f' % (best_cfg, best_score))

	return

In [ ]:
p_values=[0,1,2,3]
d_values=[1,2]
q_values=[0,1,2,3]
warnings.filterwarnings("ignore")

evaluate_models(sample_flatten,p_values,d_values,q_values)    

[70200. 71100. 70100. 70700. 69800.]
[69874.00276429 69773.77802272 69851.21729171 69737.04186444
 69740.93102896]


In [8]:
sample_name = 'sample_submission.csv'
sample_submission = pd.read_csv(os.path.join(path,sample_name))
sample_submission

Day  000060  000080  000100  000120  000150  000240  000250  000270  \
0  2021-11-01       0       0       0       0       0       0       0       0   
1  2021-11-02       0       0       0       0       0       0       0       0   
2  2021-11-03       0       0       0       0       0       0       0       0   
3  2021-11-04       0       0       0       0       0       0       0       0   
4  2021-11-05       0       0       0       0       0       0       0       0   
5  2021-11-29       0       0       0       0       0       0       0       0   
6  2021-11-30       0       0       0       0       0       0       0       0   
7  2021-12-01       0       0       0       0       0       0       0       0   
8  2021-12-02       0       0       0       0       0       0       0       0   
9  2021-12-03       0       0       0       0       0       0       0       0   

   000660  ...  330860  336260  336370  347860  348150  348210  352820  \
0       0  ...       0       0       0       0       0       0       0   
1       0  ...       0       0       0       0       0       0       0   
2       0  ...       0       0       0       0       0       0       0   
3       0  ...       0       0       0       0       0       0       0   
4       0  ...       0       0       0       0       0       0       0   
5       0  ...       0       0       0       0       0       0       0   
6       0  ...       0       0       0       0       0       0       0   
7       0  ...       0       0       0       0       0       0       0   
8       0  ...       0       0       0       0       0       0       0   
9       0  ...       0       0       0       0       0       0       0   

   357780  363280  950130  
0       0       0       0  
1       0       0       0  
2       0       0       0  
3       0       0       0  
4       0       0       0  
5       0       0       0  
6       0       0       0  
7       0       0       0  
8       0       0       0  
9       0       0       0  

[10 rows x 371 columns]

In [9]:

for code in tqdm(stock_list['종목코드'].values):
    data = fdr.DataReader(code, start = start_date, end = end_date)[['Close']].reset_index()
    data = pd.merge(Business_days, data, how = 'outer')
    data['weekday'] = data.Date.apply(lambda x : x.weekday())
    data['weeknum'] = data.Date.apply(lambda x : x.strftime('%V'))
    data.Close = data.Close.ffill()
    data = pd.pivot_table(data = data, values = 'Close', columns = 'weekday', index = 'weeknum')
    
    data_flatten = np.ravel(data.to_numpy())
    
    model=ARIMA(data_flatten,order=(0,2,1))
    model_fit=model.fit()

    predictions=model_fit.forecast(steps=5)
    print(predictions)
    # break
    sample_submission.loc[0:4,code] = predictions
sample_submission.isna().sum().sum()

  0%|          | 1/370 [00:00<02:12,  2.79it/s]

[68952.16670852 68104.33341704 67256.50012556 66408.66683409
 65560.83354261]


  1%|          | 2/370 [00:00<02:20,  2.63it/s]

[100797.35853299  98594.71706598  96392.07559897  94189.43413195
  91986.79266494]


  1%|          | 3/370 [00:01<02:07,  2.88it/s]

[401911.04493013 396822.08986027 391733.1347904  386644.17972053
 381555.22465067]


  1%|          | 4/370 [00:01<02:00,  3.05it/s]

[124939.23886868 124378.47773737 123817.71660605 123256.95547473
 122696.19434341]


  1%|▏         | 5/370 [00:01<01:53,  3.23it/s]

[856611.04762058 842222.09524117 827833.14286175 813444.19048234
 799055.23810292]


  2%|▏         | 6/370 [00:01<01:58,  3.07it/s]

[62698.41356401 61396.82712803 60095.24069204 58793.65425605
 57492.06782007]


  2%|▏         | 7/370 [00:02<01:58,  3.06it/s]

[828003.14472456 820006.28944911 812009.43417367 804012.57889822
 796015.72362278]


  2%|▏         | 8/370 [00:02<01:55,  3.13it/s]

[722936.20309507 711872.40619014 700808.60928521 689744.81238028
 678681.01547534]


  2%|▏         | 9/370 [00:02<01:51,  3.24it/s]

[205923.16623698 203846.33247396 201769.49871094 199692.66494792
 197615.8311849 ]


  3%|▎         | 10/370 [00:03<01:43,  3.47it/s]

[186946.71061979 173393.42123958 159840.13185937 146286.84247915
 132733.55309894]


  3%|▎         | 11/370 [00:03<01:49,  3.28it/s]

[85052.13606261 85004.27212522 84956.40818783 84908.54425045
 84860.68031306]


  3%|▎         | 12/370 [00:03<01:46,  3.37it/s]

[290755.03670078 285510.07340157 280265.11010235 275020.14680314
 269775.18350392]


  4%|▎         | 13/370 [00:04<01:42,  3.47it/s]

[119249.34625561 117998.69251123 116748.03876684 115497.38502246
 114246.73127807]


  4%|▍         | 14/370 [00:04<01:36,  3.69it/s]

[110977.25165413 107954.50330827 104931.7549624  101909.00661654
  98886.25827067]


  4%|▍         | 15/370 [00:04<01:42,  3.45it/s]

[241571.30751122 231142.61502244 220713.92253366 210285.23004488
 199856.5375561 ]


  4%|▍         | 16/370 [00:04<01:47,  3.30it/s]

[239797.78332842 237095.56665684 234393.34998526 231691.13331369
 228988.91664211]


  5%|▍         | 17/370 [00:05<01:59,  2.94it/s]

[1158887.58589434 1146775.17178868 1134662.75768303 1122550.34357737
 1110437.92947171]


  5%|▍         | 18/370 [00:05<01:52,  3.14it/s]

[309499.83148311 309499.66296622 309499.49444932 309499.32593243
 309499.15741554]


  5%|▌         | 19/370 [00:05<01:51,  3.14it/s]

[55574.01326743 54548.02653486 53522.03980229 52496.05306972
 51470.06633715]


  5%|▌         | 20/370 [00:06<01:53,  3.09it/s]

[37723.78758216 37197.57516433 36671.36274649 36145.15032865
 35618.93791081]


  6%|▌         | 21/370 [00:06<01:43,  3.38it/s]

[238849.86327877 234699.72655753 230549.5898363  226399.45311506
 222249.31639383]


  6%|▌         | 22/370 [00:06<01:38,  3.54it/s]

[631933.89748716 636867.79497433 641801.69246149 646735.58994866
 651669.48743582]


  6%|▌         | 23/370 [00:07<01:43,  3.35it/s]

[26410.78392099 26171.56784198 25932.35176298 25693.13568397
 25453.91960496]


  6%|▋         | 24/370 [00:07<02:28,  2.33it/s]

[22592.55895696 22585.11791392 22577.67687088 22570.23582784
 22562.7947848 ]


  7%|▋         | 25/370 [00:08<02:15,  2.55it/s]

[65701.86123871 64103.72247742 62505.58371612 60907.44495483
 59309.30619354]


  7%|▋         | 26/370 [00:08<02:11,  2.61it/s]

[151430.82820058 149861.65640115 148292.48460173 146723.31280231
 145154.14100288]


  7%|▋         | 27/370 [00:08<02:04,  2.76it/s]

[152539.87712185 146079.7542437  139619.63136555 133159.5084874
 126699.38560924]


  8%|▊         | 28/370 [00:09<01:52,  3.04it/s]

[178215.48941714 174930.97883427 171646.46825141 168361.95766854
 165077.44708568]


  8%|▊         | 29/370 [00:09<01:48,  3.16it/s]

[44531.00767008 44062.01534016 43593.02301024 43124.03068032
 42655.0383504 ]


  8%|▊         | 30/370 [00:09<01:41,  3.34it/s]

[122863.33747893 122226.67495785 121590.01243678 120953.34991571
 120316.68739464]


  8%|▊         | 31/370 [00:09<01:40,  3.39it/s]

[144529.98403002 143559.96806004 142589.95209006 141619.93612008
 140649.9201501 ]
[335819.32271556 336638.64543112 337457.96814669 338277.29086225
 339096.61357781]


  9%|▉         | 33/370 [00:10<01:45,  3.20it/s]

[24479.97923497 24559.95846994 24639.9377049  24719.91693987
 24799.89617484]


  9%|▉         | 34/370 [00:10<01:44,  3.22it/s]

[101950.88314705 101401.7662941  100852.64944115 100303.5325882
  99754.41573525]


  9%|▉         | 35/370 [00:11<01:49,  3.06it/s]

[80695.35872808 80290.71745616 79886.07618423 79481.43491231
 79076.79364039]


 10%|▉         | 36/370 [00:11<01:52,  2.97it/s]

[30361.73014007 30273.46028013 30185.1904202  30096.92056027
 30008.65070033]


 10%|█         | 37/370 [00:12<02:14,  2.47it/s]

[225591.00369025 220182.00738051 214773.01107076 209364.01476102
 203955.01845127]


 10%|█         | 38/370 [00:12<02:00,  2.75it/s]

[543470.10637226 549940.21274452 556410.31911678 562880.42548903
 569350.53186129]


 11%|█         | 39/370 [00:12<01:59,  2.77it/s]

[103531.5195603  104063.03912061 104594.55868091 105126.07824122
 105657.59780152]
[92239.74756297 89879.49512594 87519.24268892 85158.99025189
 82798.73781486]


 11%|█         | 41/370 [00:13<01:42,  3.22it/s]

[220103.37229925 215706.7445985  211310.11689775 206913.489197
 202516.86149625]


 11%|█▏        | 42/370 [00:13<01:40,  3.26it/s]

[30464.64184659 30429.28369319 30393.92553978 30358.56738637
 30323.20923297]


 12%|█▏        | 43/370 [00:14<03:23,  1.61it/s]

[14398.97530145 14397.95060291 14396.92590436 14395.90120582
 14394.87650727]


 12%|█▏        | 44/370 [00:15<02:53,  1.88it/s]

[19778.87526384 19857.75052768 19936.62579153 20015.50105537
 20094.37631921]


 12%|█▏        | 45/370 [00:15<02:33,  2.12it/s]

[13268.7008428  13287.4016856  13306.1025284  13324.80337119
 13343.50421399]


 12%|█▏        | 46/370 [00:15<02:19,  2.32it/s]

[40121.18745707 39392.37491414 38663.56237122 37934.74982829
 37205.93728536]


 13%|█▎        | 47/370 [00:16<02:04,  2.60it/s]

[11061.9474003  11073.89480061 11085.84220091 11097.78960122
 11109.73700152]


 13%|█▎        | 48/370 [00:16<01:59,  2.68it/s]

[165509.02427121 163518.04854241 161527.07281362 159536.09708483
 157545.12135603]


 13%|█▎        | 49/370 [00:16<01:53,  2.82it/s]

[44090.93133619 43731.86267237 43372.79400856 43013.72534474
 42654.65668093]


 14%|█▎        | 50/370 [00:17<01:59,  2.68it/s]

[373503.14376356 367006.28752711 360509.43129067 354012.57505422
 347515.71881778]


 14%|█▍        | 51/370 [00:17<01:54,  2.78it/s]

[14363.27377988 14376.54755975 14389.82133963 14403.0951195
 14416.36889938]


 14%|█▍        | 52/370 [00:18<02:26,  2.18it/s]

[170850.96520321 169701.93040642 168552.89560963 167403.86081284
 166254.82601606]


 14%|█▍        | 53/370 [00:18<02:50,  1.86it/s]

[79235.52424776 79071.04849552 78906.57274328 78742.09699104
 78577.6212388 ]


 15%|█▍        | 54/370 [00:19<02:27,  2.14it/s]

[50161.20012017 50022.40024033 49883.6003605  49744.80048067
 49606.00060084]


 15%|█▍        | 55/370 [00:19<02:06,  2.50it/s]

[40735.49571546 40120.99143093 39506.48714639 38891.98286186
 38277.47857732]


 15%|█▌        | 56/370 [00:19<01:55,  2.71it/s]

[8677.10321296 8674.20642592 8671.30963888 8668.41285183 8665.51606479]


 15%|█▌        | 57/370 [00:20<01:46,  2.93it/s]

[27815.73389186 27831.46778373 27847.20167559 27862.93556745
 27878.66945932]


 16%|█▌        | 58/370 [00:20<01:49,  2.86it/s]

[86857.19383818 86714.38767635 86571.58151453 86428.7753527
 86285.96919088]


 16%|█▌        | 59/370 [00:20<01:41,  3.06it/s]

[62881.42239984 62562.84479967 62244.26719951 61925.68959934
 61607.11199918]


 16%|█▌        | 60/370 [00:21<01:39,  3.10it/s]

[210228.70615242 210957.41230484 211686.11845726 212414.82460968
 213143.5307621 ]


 16%|█▋        | 61/370 [00:21<01:39,  3.09it/s]

[55859.96366586 54719.92733172 53579.89099758 52439.85466344
 51299.81832931]


 17%|█▋        | 62/370 [00:22<02:08,  2.40it/s]

[48606.90734807 47613.81469613 46620.7220442  45627.62939226
 44634.53674033]


 17%|█▋        | 63/370 [00:22<02:23,  2.14it/s]

[24869.37648044 24938.75296087 25008.12944131 25077.50592174
 25146.88240218]


 17%|█▋        | 64/370 [00:22<02:07,  2.41it/s]

[169498.17733042 170996.35466083 172494.53199125 173992.70932166
 175490.88665208]


 18%|█▊        | 65/370 [00:23<01:53,  2.68it/s]

[116912.43788033 115824.87576066 114737.31364098 113649.75152131
 112562.18940164]


 18%|█▊        | 66/370 [00:23<01:45,  2.89it/s]

[37825.38880686 37600.77761372 37376.16642059 37151.55522745
 36926.94403431]


 18%|█▊        | 67/370 [00:23<01:52,  2.70it/s]

[52959.58944097 51119.17888193 49278.7683229  47438.35776387
 45597.94720483]


 18%|█▊        | 68/370 [00:24<02:00,  2.50it/s]

[59005.36654962 58110.73309924 57216.09964885 56321.46619847
 55426.83274809]


 19%|█▊        | 69/370 [00:24<01:55,  2.61it/s]

[38412.02743624 37999.05487249 37586.08230873 37173.10974498
 36760.13718122]


 19%|█▉        | 70/370 [00:25<01:48,  2.76it/s]

[138496.464702 134992.929404 131489.394106 127985.858808 124482.32351 ]


 19%|█▉        | 71/370 [00:25<01:44,  2.86it/s]

[41680.5986069  41111.1972138  40541.7958207  39972.39442761
 39402.99303451]


 19%|█▉        | 72/370 [00:25<01:40,  2.97it/s]

[7855.80734774 7861.61469549 7867.42204323 7873.22939097 7879.03673872]


 20%|█▉        | 73/370 [00:25<01:40,  2.95it/s]

[33967.95050693 33685.90101387 33403.8515208  33121.80202774
 32839.75253467]


 20%|██        | 74/370 [00:26<01:34,  3.14it/s]

[6014.69084474 6009.38168947 6004.07253421 5998.76337895 5993.45422368]


 20%|██        | 75/370 [00:26<01:35,  3.07it/s]

[32293.60992769 31887.21985539 31480.82978308 31074.43971077
 30668.04963846]


 21%|██        | 76/370 [00:26<01:38,  2.98it/s]

[57070.86446615 54941.7289323  52812.59339845 50683.4578646
 48554.32233075]


 21%|██        | 77/370 [00:27<02:18,  2.12it/s]

[46848.18142414 46346.36284827 45844.54427241 45342.72569655
 44840.90712068]


 21%|██        | 78/370 [00:28<02:08,  2.27it/s]

[259555.4244488  255110.8488976  250666.2733464  246221.69779519
 241777.12224399]


 22%|██▏       | 80/370 [00:28<01:38,  2.95it/s]

[96530.15567583 95160.31135166 93790.46702749 92420.62270333
 91050.77837916]
[593804.14091804 590608.28183607 587412.42275411 584216.56367214
 581020.70459018]


 22%|██▏       | 81/370 [00:28<01:36,  3.00it/s]

[41344.88770735 41339.77541471 41334.66312206 41329.55082942
 41324.43853677]


 22%|██▏       | 82/370 [00:29<01:33,  3.09it/s]

[98936.19613514 97372.39227027 95808.58840541 94244.78454054
 92680.98067568]


 22%|██▏       | 83/370 [00:29<01:28,  3.23it/s]

[31973.2671586 31746.5343172 31519.8014758 31293.0686344 31066.335793 ]


 23%|██▎       | 84/370 [00:29<01:31,  3.12it/s]

[86918.61015547 86437.22031094 85955.8304664  85474.44062187
 84993.05077734]


 23%|██▎       | 85/370 [00:30<01:34,  3.00it/s]

[13160.86070278 13171.72140555 13182.58210833 13193.44281111
 13204.30351388]


 23%|██▎       | 86/370 [00:30<01:27,  3.23it/s]

[69374.16390236 69348.32780473 69322.49170709 69296.65560946
 69270.81951182]


 24%|██▎       | 87/370 [00:30<01:36,  2.93it/s]

[26168.56485802 26537.12971605 26905.69457407 27274.2594321
 27642.82429012]


 24%|██▍       | 88/370 [00:31<01:25,  3.32it/s]

[115054.57932838 113609.15865676 112163.73798514 110718.31731352
 109272.8966419 ]


 24%|██▍       | 89/370 [00:31<01:29,  3.13it/s]

[278967.09862396 283434.19724792 287901.29587188 292368.39449584
 296835.4931198 ]


 24%|██▍       | 90/370 [00:31<01:26,  3.25it/s]

[4663.32910976 4666.65821952 4669.98732928 4673.31643904 4676.64554881]


 25%|██▍       | 91/370 [00:32<02:15,  2.06it/s]

[48542.42869457 45284.85738914 42027.28608371 38769.71477828
 35512.14347285]


 25%|██▍       | 92/370 [00:32<02:00,  2.30it/s]

[76689.31198748 77678.62397495 78667.93596243 79657.2479499
 80646.55993738]


 25%|██▌       | 93/370 [00:33<01:51,  2.49it/s]

[43872.5428524  43445.0857048  43017.62855721 42590.17140961
 42162.71426201]


 25%|██▌       | 94/370 [00:33<01:46,  2.60it/s]

[21668.80392064 21637.60784128 21606.41176191 21575.21568255
 21544.01960319]


 26%|██▌       | 95/370 [00:33<01:35,  2.89it/s]

[30301.02741825 30052.0548365  29803.08225475 29554.109673
 29305.13709126]


 26%|██▌       | 96/370 [00:34<01:29,  3.07it/s]

[33223.41792599 33196.83585197 33170.25377796 33143.67170395
 33117.08962994]


 26%|██▌       | 97/370 [00:34<01:24,  3.22it/s]

[52682.8693383 53165.7386766 53648.6080149 54131.4773532 54614.3466915]


 26%|██▋       | 98/370 [00:34<01:21,  3.33it/s]

[36576.40901798 36052.81803595 35529.22705393 35005.63607191
 34482.04508988]


 27%|██▋       | 99/370 [00:34<01:15,  3.58it/s]

[16417.10975145 16434.2195029  16451.32925435 16468.4390058
 16485.54875725]


 27%|██▋       | 100/370 [00:35<01:20,  3.35it/s]

[105299.97461035 105599.9492207  105899.92383106 106199.89844141
 106499.87305176]


 27%|██▋       | 101/370 [00:35<01:19,  3.40it/s]

[102767.25819918 100534.51639837  98301.77459755  96069.03279673
  93836.29099592]


 28%|██▊       | 102/370 [00:36<01:48,  2.48it/s]

[6239.61878274 6229.23756549 6218.85634823 6208.47513098 6198.09391372]


 28%|██▊       | 103/370 [00:36<01:50,  2.41it/s]

[81803.08815727 80306.17631454 78809.26447181 77312.35262908
 75815.44078635]


 28%|██▊       | 104/370 [00:37<01:43,  2.57it/s]

[34127.20186351 33654.40372703 33181.60559054 32708.80745406
 32236.00931757]


 28%|██▊       | 105/370 [00:37<01:36,  2.74it/s]

[127568.23835175 125636.4767035  123704.71505526 121772.95340701
 119841.19175876]


 29%|██▊       | 106/370 [00:37<01:33,  2.82it/s]

[3479.939919 3484.879838 3489.819757 3494.759676 3499.699595]


 29%|██▉       | 107/370 [00:38<01:43,  2.54it/s]

[320880.62470873 312761.24941746 304641.87412618 296522.49883491
 288403.12354364]


 29%|██▉       | 108/370 [00:38<01:33,  2.79it/s]

[328386.51787265 323773.03574529 319159.55361794 314546.07149059
 309932.58936323]


 29%|██▉       | 109/370 [00:38<01:27,  3.00it/s]

[375600.94567663 367701.89135326 359802.83702989 351903.78270653
 344004.72838316]


 30%|██▉       | 110/370 [00:38<01:23,  3.12it/s]

[27778.29049819 27856.58099638 27934.87149457 28013.16199276
 28091.45249095]


 30%|███       | 111/370 [00:39<01:17,  3.33it/s]

[175008.08158383 170016.16316767 165024.2447515  160032.32633534
 155040.40791917]


 30%|███       | 112/370 [00:39<01:18,  3.28it/s]

[61758.75466855 61117.50933709 60476.26400564 59835.01867418
 59193.77334273]


 31%|███       | 113/370 [00:39<01:20,  3.20it/s]

[23878.38435718 23906.76871435 23935.15307153 23963.53742871
 23991.92178589]


 31%|███       | 114/370 [00:40<01:13,  3.49it/s]

[159552.52630013 157605.05260027 155657.5789004  153710.10520054
 151762.63150067]


 31%|███       | 115/370 [00:40<01:18,  3.27it/s]

[100442.21327899  99384.42655799  98326.63983698  97268.85311597
  96211.06639497]


 31%|███▏      | 116/370 [00:40<01:15,  3.36it/s]

[57715.90868608 57931.81737216 58147.72605823 58363.63474431
 58579.54343039]


 32%|███▏      | 117/370 [00:40<01:11,  3.53it/s]

[711370.68986684 713741.37973368 716112.06960052 718482.75946735
 720853.44933419]


 32%|███▏      | 118/370 [00:41<01:14,  3.40it/s]

[244973.74302568 241947.48605135 238921.22907703 235894.9721027
 232868.71512838]


 32%|███▏      | 119/370 [00:41<01:27,  2.86it/s]

[22260.91345504 22021.82691007 21782.74036511 21543.65382015
 21304.56727519]


KeyboardInterrupt: 

In [ ]:
sample_submission.columns

Index(['Day', '000060', '000080', '000100', '000120', '000150', '000240',
       '000250', '000270', '000660',
       ...
       '330860', '336260', '336370', '347860', '348150', '348210', '352820',
       '357780', '363280', '950130'],
      dtype='object', length=371)

In [ ]:
columns = list(sample_submission.columns[1:])

columns = ['Day'] + [str(x).zfill(6) for x in columns]

sample_submission.columns = columns

In [ ]:
sample_submission.to_csv('BASELINE_Linear.csv',index=False)

In [ ]:
sample_submission

Day        000060        000080        000100         000120  \
0  2021-11-01  27778.290498  34287.329892  59005.366550  138496.464702   
1  2021-11-02  27856.580996  33774.659785  58110.733099  134992.929404   
2  2021-11-03  27934.871495  33261.989677  57216.099649  131489.394106   
3  2021-11-04  28013.161993  32749.319570  56321.466198  127985.858808   
4  2021-11-05  28091.452491  32236.649462  55426.832748  124482.323510   
5  2021-11-29      0.000000      0.000000      0.000000       0.000000   
6  2021-11-30      0.000000      0.000000      0.000000       0.000000   
7  2021-12-01      0.000000      0.000000      0.000000       0.000000   
8  2021-12-02      0.000000      0.000000      0.000000       0.000000   
9  2021-12-03      0.000000      0.000000      0.000000       0.000000   

          000150        000240        000250        000270         000660  \
0  103234.899188  16683.644556  45469.412046  85052.136063  100797.358533   
1  103469.798377  16667.289112  43888.824092  85004.272125   98594.717066   
2  103704.697565  16650.933668  42308.236138  84956.408188   96392.075599   
3  103939.596753  16634.578224  40727.648185  84908.544250   94189.434132   
4  104174.495941  16618.222780  39147.060231  84860.680313   91986.792665   
5       0.000000      0.000000      0.000000      0.000000       0.000000   
6       0.000000      0.000000      0.000000      0.000000       0.000000   
7       0.000000      0.000000      0.000000      0.000000       0.000000   
8       0.000000      0.000000      0.000000      0.000000       0.000000   
9       0.000000      0.000000      0.000000      0.000000       0.000000   

   ...        330860        336260        336370        347860        348150  \
0  ...  49491.403714  52682.869338  82828.251387  35350.993921  25600.784437   
1  ...  49882.807427  53165.738677  83356.502774  34601.987842  25251.568874   
2  ...  50274.211141  53648.608015  83884.754161  33852.981763  24902.353311   
3  ...  50665.614855  54131.477353  84413.005547  33103.975684  24553.137748   
4  ...  51057.018568  54614.346691  84941.256934  32354.969605  24203.922185   
5  ...      0.000000      0.000000      0.000000      0.000000      0.000000   
6  ...      0.000000      0.000000      0.000000      0.000000      0.000000   
7  ...      0.000000      0.000000      0.000000      0.000000      0.000000   
8  ...      0.000000      0.000000      0.000000      0.000000      0.000000   
9  ...      0.000000      0.000000      0.000000      0.000000      0.000000   

         348210         352820         357780        363280        950130  
0  52225.585465  335819.322716  259632.806738  27015.742529  17086.094982  
1  51351.170930  336638.645431  257665.613475  26881.485059  17072.189963  
2  50476.756395  337457.968147  255698.420213  26747.227588  17058.284945  
3  49602.341860  338277.290862  253731.226951  26612.970118  17044.379927  
4  48727.927324  339096.613578  251764.033689  26478.712647  17030.474908  
5      0.000000       0.000000       0.000000      0.000000      0.000000  
6      0.000000       0.000000       0.000000      0.000000      0.000000  
7      0.000000       0.000000       0.000000      0.000000      0.000000  
8      0.000000       0.000000       0.000000      0.000000      0.000000  
9      0.000000       0.000000       0.000000      0.000000      0.000000  

[10 rows x 371 columns]

In [ ]:

start_date = '20211101'
end_date = '20211105'

start_weekday = pd.to_datetime(start_date).weekday()
max_weeknum = pd.to_datetime(end_date).strftime('%V')
Business_days = pd.DataFrame(pd.date_range(start_date,end_date,freq='B'), columns = ['Date'])

print(f'WEEKDAY of "start_date" : {start_weekday}')
print(f'NUM of WEEKS to "end_date" : {max_weeknum}')
print(f'HOW MANY "Business_days" : {Business_days.shape}', )


real=[]
real_data=pd.read_csv('C:\\Users\\user\\Desktop\\computing\\outside\\dacon\\stock_predict2\\open\\sample_submission.csv')
for code in tqdm(stock_list['종목코드'].values):
    data = fdr.DataReader(code, start = start_date, end = end_date)[['Close']].reset_index()
    data = pd.merge(Business_days, data, how = 'outer')
    data['weekday'] = data.Date.apply(lambda x : x.weekday())
    data['weeknum'] = data.Date.apply(lambda x : x.strftime('%V'))
    data.Close = data.Close.ffill()
    data.Close = data.Close.bfill()

    real_data_close = pd.pivot_table(data = data, values = 'Close', columns = 'weekday', index = 'weeknum')
    real_data_close_flatten = np.ravel(real_data_close.to_numpy())
    # print(real_data_close_flatten)
    

    real_data.loc[:4,code]=real_data_close_flatten


type(real_data)
type(sample_submission)

label_np = real_data.to_numpy()[0:5,1:]
pred_np = sample_submission.to_numpy()[0:5, 1:]
print(pred_np)


result=np.mean(abs(label_np-pred_np)/label_np)*100
print(result)

WEEKDAY of "start_date" : 0
NUM of WEEKS to "end_date" : 44
HOW MANY "Business_days" : (5, 1)


100%|██████████| 370/370 [01:27<00:00,  4.21it/s]

[[27778.290498189148 34287.32989242792 59005.36654961816 ...
  259632.80673770854 27015.742529463645 17086.094981690447]
 [27856.580996378296 33774.659784855845 58110.73309923631 ...
  257665.61347541705 26881.48505892729 17072.189963380893]
 [27934.871494567444 33261.98967728377 57216.09964885448 ...
  255698.42021312556 26747.227588390935 17058.28494507134]
 [28013.16199275659 32749.319569711693 56321.46619847264 ...
  253731.22695083407 26612.97011785458 17044.379926761787]
 [28091.45249094574 32236.64946213962 55426.832748090805 ...
  251764.03368854258 26478.712647318225 17030.474908452234]]
4.882870265112119
